"""
AegisCare Enterprise Patient Management System - Medication Formulary Monographs
Clinical pharmacology, dosage regimens, mechanisms of action, and adverse reactions.
"""

from typing import Dict, List, Optional

FORMULARY_MONOGRAPHS: Dict[str, Dict] = {
    "AMOXICILLIN": {
        "generic_name": "AMOXICILLIN",
        "brand_name": "Amoxil",
        "therapeutic_category": "ANTIBIOTIC",
        "standard_strength": "500mg",
        "dosage_form": "Oral Capsule",
        "mechanism_of_action": "Inhibits bacterial cell wall synthesis by binding to PBPs",
        "standard_dosage_regimen": "500mg PO TID for 7-10 days",
        "adverse_reactions": "Rash, diarrhea, nausea, allergic anaphylaxis",
        "requires_monitoring": True,
    },
    "AZITHROMYCIN": {
        "generic_name": "AZITHROMYCIN",
        "brand_name": "Zithromax",
        "therapeutic_category": "ANTIBIOTIC",
        "standard_strength": "250mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Macrolide that binds to 50S ribosomal subunit inhibiting protein synthesis",
        "standard_dosage_regimen": "500mg Day 1, then 250mg PO QD for 4 days",
        "adverse_reactions": "QT prolongation, GI upset, hepatotoxicity",
        "requires_monitoring": True,
    },
    "CIPROFLOXACIN": {
        "generic_name": "CIPROFLOXACIN",
        "brand_name": "Cipro",
        "therapeutic_category": "ANTIBIOTIC",
        "standard_strength": "500mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Fluoroquinolone inhibiting DNA gyrase and topoisomerase IV",
        "standard_dosage_regimen": "500mg PO BID for 7-14 days",
        "adverse_reactions": "Tendon rupture, CNS excitation, QT prolongation",
        "requires_monitoring": True,
    },
    "LISINOPRIL": {
        "generic_name": "LISINOPRIL",
        "brand_name": "Prinivil",
        "therapeutic_category": "ANTIHYPERTENSIVE",
        "standard_strength": "10mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "ACE inhibitor preventing conversion of angiotensin I to angiotensin II",
        "standard_dosage_regimen": "10-40mg PO QD",
        "adverse_reactions": "Dry chronic cough, hyperkalemia, angioedema, hypotension",
        "requires_monitoring": True,
    },
    "AMLODIPINE": {
        "generic_name": "AMLODIPINE",
        "brand_name": "Norvasc",
        "therapeutic_category": "ANTIHYPERTENSIVE",
        "standard_strength": "5mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Dihydropyridine calcium channel blocker inducing arterial vasodilation",
        "standard_dosage_regimen": "5-10mg PO QD",
        "adverse_reactions": "Peripheral pedal edema, flushing, dizziness, reflex tachycardia",
        "requires_monitoring": True,
    },
    "METOPROLOL": {
        "generic_name": "METOPROLOL",
        "brand_name": "Lopressor",
        "therapeutic_category": "ANTIHYPERTENSIVE",
        "standard_strength": "50mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Selective beta-1 adrenergic receptor antagonist reducing cardiac output",
        "standard_dosage_regimen": "50-100mg PO BID",
        "adverse_reactions": "Bradycardia, fatigue, bronchospasm in reactive airways, depression",
        "requires_monitoring": True,
    },
    "ATORVASTATIN": {
        "generic_name": "ATORVASTATIN",
        "brand_name": "Lipitor",
        "therapeutic_category": "LIPID_LOWERING",
        "standard_strength": "20mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "HMG-CoA reductase inhibitor reducing hepatic cholesterol synthesis",
        "standard_dosage_regimen": "20-80mg PO QHS",
        "adverse_reactions": "Myalgia, elevated hepatic transaminases, rhabdomyolysis",
        "requires_monitoring": True,
    },
    "METFORMIN": {
        "generic_name": "METFORMIN",
        "brand_name": "Glucophage",
        "therapeutic_category": "ANTIDIABETIC",
        "standard_strength": "500mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Biguanide reducing hepatic gluconeogenesis and improving insulin sensitivity",
        "standard_dosage_regimen": "500-1000mg PO BID with meals",
        "adverse_reactions": "GI discomfort, metallic taste, lactic acidosis in renal impairment",
        "requires_monitoring": True,
    },
    "GLIMEPIRIDE": {
        "generic_name": "GLIMEPIRIDE",
        "brand_name": "Amaryl",
        "therapeutic_category": "ANTIDIABETIC",
        "standard_strength": "2mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Sulfonylurea stimulating pancreatic beta-cell insulin secretion",
        "standard_dosage_regimen": "1-4mg PO QD with breakfast",
        "adverse_reactions": "Hypoglycemia, weight gain, allergic cutaneous reactions",
        "requires_monitoring": True,
    },
    "OMEPRAZOLE": {
        "generic_name": "OMEPRAZOLE",
        "brand_name": "Prilosec",
        "therapeutic_category": "GASTROPROTECTIVE",
        "standard_strength": "20mg",
        "dosage_form": "Delayed-Release Capsule",
        "mechanism_of_action": "Irreversible proton pump inhibitor suppressing gastric acid secretion",
        "standard_dosage_regimen": "20-40mg PO QD 30 min before breakfast",
        "adverse_reactions": "Headache, C. diff diarrhea, hypomagnesemia with prolonged use",
        "requires_monitoring": True,
    },
    "LEVOTHYROXINE": {
        "generic_name": "LEVOTHYROXINE",
        "brand_name": "Synthroid",
        "therapeutic_category": "THYROID_HORMONE",
        "standard_strength": "50mcg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Synthetic T4 hormone restoring euthyroid metabolic balance",
        "standard_dosage_regimen": "50-125mcg PO QD on empty stomach",
        "adverse_reactions": "Palpitations, weight loss, heat intolerance if over-replaced",
        "requires_monitoring": True,
    },
    "WARFARIN": {
        "generic_name": "WARFARIN",
        "brand_name": "Coumadin",
        "therapeutic_category": "ANTICOAGULANT",
        "standard_strength": "5mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Vitamin K epoxide reductase antagonist depleting factors II, VII, IX, X",
        "standard_dosage_regimen": "Titrated to target INR (usually 2.0-3.0)",
        "adverse_reactions": "Major bleeding, skin necrosis, extensive drug-food interactions",
        "requires_monitoring": True,
    },
    "APIXABAN": {
        "generic_name": "APIXABAN",
        "brand_name": "Eliquis",
        "therapeutic_category": "ANTICOAGULANT",
        "standard_strength": "5mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Direct factor Xa inhibitor preventing thrombin formation",
        "standard_dosage_regimen": "5mg PO BID (2.5mg BID in renal/age criteria)",
        "adverse_reactions": "Bleeding, hematoma formation, thrombocytopenia",
        "requires_monitoring": True,
    },
    "SALBUTAMOL": {
        "generic_name": "SALBUTAMOL",
        "brand_name": "Ventolin",
        "therapeutic_category": "BRONCHODILATOR",
        "standard_strength": "100mcg/puff",
        "dosage_form": "Metered Dose Inhaler",
        "mechanism_of_action": "Short-acting beta-2 agonist relaxing bronchial smooth muscle",
        "standard_dosage_regimen": "2 puffs inhaled Q4-6H PRN acute bronchospasm",
        "adverse_reactions": "Tremor, tachycardia, hypokalemia with high doses",
        "requires_monitoring": True,
    },
    "FLUTICASONE": {
        "generic_name": "FLUTICASONE",
        "brand_name": "Flovent",
        "therapeutic_category": "CORTICOSTEROID",
        "standard_strength": "110mcg/puff",
        "dosage_form": "Metered Dose Inhaler",
        "mechanism_of_action": "Inhaled corticosteroid reducing airway inflammatory infiltration",
        "standard_dosage_regimen": "1-2 puffs inhaled BID; rinse mouth after use",
        "adverse_reactions": "Oral candidiasis (thrush), dysphonia, pharyngitis",
        "requires_monitoring": True,
    },
    "PARACETAMOL": {
        "generic_name": "PARACETAMOL",
        "brand_name": "Tylenol",
        "therapeutic_category": "ANALGESIC",
        "standard_strength": "500mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Central COX inhibitor providing antipyresis and analgesia",
        "standard_dosage_regimen": "500-1000mg PO Q4-6H PRN (max 3000mg/day)",
        "adverse_reactions": "Hepatotoxicity in overdose or chronic alcohol usage",
        "requires_monitoring": True,
    },
    "IBUPROFEN": {
        "generic_name": "IBUPROFEN",
        "brand_name": "Advil",
        "therapeutic_category": "NSAID",
        "standard_strength": "400mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Non-selective COX-1/COX-2 inhibitor reducing prostaglandin synthesis",
        "standard_dosage_regimen": "400-800mg PO TID with food",
        "adverse_reactions": "Gastric mucosal ulceration, renal impairment, fluid retention",
        "requires_monitoring": True,
    },
    "TRAMADOL": {
        "generic_name": "TRAMADOL",
        "brand_name": "Ultram",
        "therapeutic_category": "ANALGESIC_OPIOID",
        "standard_strength": "50mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Centrally acting mu-opioid agonist and SNRI for moderate pain",
        "standard_dosage_regimen": "50-100mg PO Q6H PRN",
        "adverse_reactions": "Drowsiness, constipation, risk of serotonin syndrome, addiction liability",
        "requires_monitoring": True,
    },
    "ONDANSETRON": {
        "generic_name": "ONDANSETRON",
        "brand_name": "Zofran",
        "therapeutic_category": "ANTIEMETIC",
        "standard_strength": "4mg",
        "dosage_form": "Oral Disintegrating Tablet",
        "mechanism_of_action": "Selective 5-HT3 receptor antagonist preventing emetic trigger",
        "standard_dosage_regimen": "4-8mg PO/IV Q8H PRN",
        "adverse_reactions": "Headache, constipation, QT prolongation",
        "requires_monitoring": True,
    },
    "FUROSEMIDE": {
        "generic_name": "FUROSEMIDE",
        "brand_name": "Lasix",
        "therapeutic_category": "DIURETIC",
        "standard_strength": "40mg",
        "dosage_form": "Oral Tablet",
        "mechanism_of_action": "Loop diuretic inhibiting Na-K-2Cl symporter in thick ascending loop",
        "standard_dosage_regimen": "20-80mg PO QD or BID",
        "adverse_reactions": "Hypokalemia, volume depletion, ototoxicity, hyperuricemia",
        "requires_monitoring": True,
    },
    "FORMULARY_SUBSTANCE_001": {
        "generic_name": "FORMULARY_SUBSTANCE_001",
        "brand_name": "AegisMed-1",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #1",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_002": {
        "generic_name": "FORMULARY_SUBSTANCE_002",
        "brand_name": "AegisMed-2",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #2",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_003": {
        "generic_name": "FORMULARY_SUBSTANCE_003",
        "brand_name": "AegisMed-3",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #3",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_004": {
        "generic_name": "FORMULARY_SUBSTANCE_004",
        "brand_name": "AegisMed-4",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #4",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_005": {
        "generic_name": "FORMULARY_SUBSTANCE_005",
        "brand_name": "AegisMed-5",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #5",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_006": {
        "generic_name": "FORMULARY_SUBSTANCE_006",
        "brand_name": "AegisMed-6",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #6",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_007": {
        "generic_name": "FORMULARY_SUBSTANCE_007",
        "brand_name": "AegisMed-7",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #7",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_008": {
        "generic_name": "FORMULARY_SUBSTANCE_008",
        "brand_name": "AegisMed-8",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #8",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_009": {
        "generic_name": "FORMULARY_SUBSTANCE_009",
        "brand_name": "AegisMed-9",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #9",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_010": {
        "generic_name": "FORMULARY_SUBSTANCE_010",
        "brand_name": "AegisMed-10",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #10",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_011": {
        "generic_name": "FORMULARY_SUBSTANCE_011",
        "brand_name": "AegisMed-11",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #11",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_012": {
        "generic_name": "FORMULARY_SUBSTANCE_012",
        "brand_name": "AegisMed-12",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #12",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_013": {
        "generic_name": "FORMULARY_SUBSTANCE_013",
        "brand_name": "AegisMed-13",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #13",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_014": {
        "generic_name": "FORMULARY_SUBSTANCE_014",
        "brand_name": "AegisMed-14",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #14",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_015": {
        "generic_name": "FORMULARY_SUBSTANCE_015",
        "brand_name": "AegisMed-15",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #15",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_016": {
        "generic_name": "FORMULARY_SUBSTANCE_016",
        "brand_name": "AegisMed-16",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #16",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_017": {
        "generic_name": "FORMULARY_SUBSTANCE_017",
        "brand_name": "AegisMed-17",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #17",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_018": {
        "generic_name": "FORMULARY_SUBSTANCE_018",
        "brand_name": "AegisMed-18",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #18",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_019": {
        "generic_name": "FORMULARY_SUBSTANCE_019",
        "brand_name": "AegisMed-19",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #19",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_020": {
        "generic_name": "FORMULARY_SUBSTANCE_020",
        "brand_name": "AegisMed-20",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #20",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_021": {
        "generic_name": "FORMULARY_SUBSTANCE_021",
        "brand_name": "AegisMed-21",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #21",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_022": {
        "generic_name": "FORMULARY_SUBSTANCE_022",
        "brand_name": "AegisMed-22",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #22",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_023": {
        "generic_name": "FORMULARY_SUBSTANCE_023",
        "brand_name": "AegisMed-23",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #23",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_024": {
        "generic_name": "FORMULARY_SUBSTANCE_024",
        "brand_name": "AegisMed-24",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #24",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_025": {
        "generic_name": "FORMULARY_SUBSTANCE_025",
        "brand_name": "AegisMed-25",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #25",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_026": {
        "generic_name": "FORMULARY_SUBSTANCE_026",
        "brand_name": "AegisMed-26",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #26",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_027": {
        "generic_name": "FORMULARY_SUBSTANCE_027",
        "brand_name": "AegisMed-27",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #27",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_028": {
        "generic_name": "FORMULARY_SUBSTANCE_028",
        "brand_name": "AegisMed-28",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #28",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_029": {
        "generic_name": "FORMULARY_SUBSTANCE_029",
        "brand_name": "AegisMed-29",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #29",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_030": {
        "generic_name": "FORMULARY_SUBSTANCE_030",
        "brand_name": "AegisMed-30",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #30",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_031": {
        "generic_name": "FORMULARY_SUBSTANCE_031",
        "brand_name": "AegisMed-31",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #31",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_032": {
        "generic_name": "FORMULARY_SUBSTANCE_032",
        "brand_name": "AegisMed-32",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #32",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_033": {
        "generic_name": "FORMULARY_SUBSTANCE_033",
        "brand_name": "AegisMed-33",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #33",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_034": {
        "generic_name": "FORMULARY_SUBSTANCE_034",
        "brand_name": "AegisMed-34",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #34",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_035": {
        "generic_name": "FORMULARY_SUBSTANCE_035",
        "brand_name": "AegisMed-35",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #35",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_036": {
        "generic_name": "FORMULARY_SUBSTANCE_036",
        "brand_name": "AegisMed-36",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #36",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_037": {
        "generic_name": "FORMULARY_SUBSTANCE_037",
        "brand_name": "AegisMed-37",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #37",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_038": {
        "generic_name": "FORMULARY_SUBSTANCE_038",
        "brand_name": "AegisMed-38",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #38",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_039": {
        "generic_name": "FORMULARY_SUBSTANCE_039",
        "brand_name": "AegisMed-39",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #39",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_040": {
        "generic_name": "FORMULARY_SUBSTANCE_040",
        "brand_name": "AegisMed-40",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #40",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_041": {
        "generic_name": "FORMULARY_SUBSTANCE_041",
        "brand_name": "AegisMed-41",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #41",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_042": {
        "generic_name": "FORMULARY_SUBSTANCE_042",
        "brand_name": "AegisMed-42",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #42",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_043": {
        "generic_name": "FORMULARY_SUBSTANCE_043",
        "brand_name": "AegisMed-43",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #43",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_044": {
        "generic_name": "FORMULARY_SUBSTANCE_044",
        "brand_name": "AegisMed-44",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #44",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_045": {
        "generic_name": "FORMULARY_SUBSTANCE_045",
        "brand_name": "AegisMed-45",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #45",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_046": {
        "generic_name": "FORMULARY_SUBSTANCE_046",
        "brand_name": "AegisMed-46",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #46",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_047": {
        "generic_name": "FORMULARY_SUBSTANCE_047",
        "brand_name": "AegisMed-47",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #47",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_048": {
        "generic_name": "FORMULARY_SUBSTANCE_048",
        "brand_name": "AegisMed-48",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #48",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_049": {
        "generic_name": "FORMULARY_SUBSTANCE_049",
        "brand_name": "AegisMed-49",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #49",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_050": {
        "generic_name": "FORMULARY_SUBSTANCE_050",
        "brand_name": "AegisMed-50",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #50",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_051": {
        "generic_name": "FORMULARY_SUBSTANCE_051",
        "brand_name": "AegisMed-51",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #51",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_052": {
        "generic_name": "FORMULARY_SUBSTANCE_052",
        "brand_name": "AegisMed-52",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #52",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_053": {
        "generic_name": "FORMULARY_SUBSTANCE_053",
        "brand_name": "AegisMed-53",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #53",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_054": {
        "generic_name": "FORMULARY_SUBSTANCE_054",
        "brand_name": "AegisMed-54",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #54",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_055": {
        "generic_name": "FORMULARY_SUBSTANCE_055",
        "brand_name": "AegisMed-55",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #55",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_056": {
        "generic_name": "FORMULARY_SUBSTANCE_056",
        "brand_name": "AegisMed-56",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #56",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_057": {
        "generic_name": "FORMULARY_SUBSTANCE_057",
        "brand_name": "AegisMed-57",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #57",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_058": {
        "generic_name": "FORMULARY_SUBSTANCE_058",
        "brand_name": "AegisMed-58",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #58",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_059": {
        "generic_name": "FORMULARY_SUBSTANCE_059",
        "brand_name": "AegisMed-59",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #59",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_060": {
        "generic_name": "FORMULARY_SUBSTANCE_060",
        "brand_name": "AegisMed-60",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #60",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_061": {
        "generic_name": "FORMULARY_SUBSTANCE_061",
        "brand_name": "AegisMed-61",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #61",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_062": {
        "generic_name": "FORMULARY_SUBSTANCE_062",
        "brand_name": "AegisMed-62",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #62",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_063": {
        "generic_name": "FORMULARY_SUBSTANCE_063",
        "brand_name": "AegisMed-63",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #63",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_064": {
        "generic_name": "FORMULARY_SUBSTANCE_064",
        "brand_name": "AegisMed-64",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #64",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_065": {
        "generic_name": "FORMULARY_SUBSTANCE_065",
        "brand_name": "AegisMed-65",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #65",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_066": {
        "generic_name": "FORMULARY_SUBSTANCE_066",
        "brand_name": "AegisMed-66",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #66",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_067": {
        "generic_name": "FORMULARY_SUBSTANCE_067",
        "brand_name": "AegisMed-67",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #67",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_068": {
        "generic_name": "FORMULARY_SUBSTANCE_068",
        "brand_name": "AegisMed-68",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #68",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_069": {
        "generic_name": "FORMULARY_SUBSTANCE_069",
        "brand_name": "AegisMed-69",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #69",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_070": {
        "generic_name": "FORMULARY_SUBSTANCE_070",
        "brand_name": "AegisMed-70",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #70",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_071": {
        "generic_name": "FORMULARY_SUBSTANCE_071",
        "brand_name": "AegisMed-71",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #71",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_072": {
        "generic_name": "FORMULARY_SUBSTANCE_072",
        "brand_name": "AegisMed-72",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #72",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_073": {
        "generic_name": "FORMULARY_SUBSTANCE_073",
        "brand_name": "AegisMed-73",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #73",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_074": {
        "generic_name": "FORMULARY_SUBSTANCE_074",
        "brand_name": "AegisMed-74",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #74",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_075": {
        "generic_name": "FORMULARY_SUBSTANCE_075",
        "brand_name": "AegisMed-75",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #75",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_076": {
        "generic_name": "FORMULARY_SUBSTANCE_076",
        "brand_name": "AegisMed-76",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #76",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_077": {
        "generic_name": "FORMULARY_SUBSTANCE_077",
        "brand_name": "AegisMed-77",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #77",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_078": {
        "generic_name": "FORMULARY_SUBSTANCE_078",
        "brand_name": "AegisMed-78",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #78",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_079": {
        "generic_name": "FORMULARY_SUBSTANCE_079",
        "brand_name": "AegisMed-79",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #79",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_080": {
        "generic_name": "FORMULARY_SUBSTANCE_080",
        "brand_name": "AegisMed-80",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #80",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_081": {
        "generic_name": "FORMULARY_SUBSTANCE_081",
        "brand_name": "AegisMed-81",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #81",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_082": {
        "generic_name": "FORMULARY_SUBSTANCE_082",
        "brand_name": "AegisMed-82",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #82",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_083": {
        "generic_name": "FORMULARY_SUBSTANCE_083",
        "brand_name": "AegisMed-83",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #83",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_084": {
        "generic_name": "FORMULARY_SUBSTANCE_084",
        "brand_name": "AegisMed-84",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #84",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_085": {
        "generic_name": "FORMULARY_SUBSTANCE_085",
        "brand_name": "AegisMed-85",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #85",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_086": {
        "generic_name": "FORMULARY_SUBSTANCE_086",
        "brand_name": "AegisMed-86",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #86",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_087": {
        "generic_name": "FORMULARY_SUBSTANCE_087",
        "brand_name": "AegisMed-87",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #87",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_088": {
        "generic_name": "FORMULARY_SUBSTANCE_088",
        "brand_name": "AegisMed-88",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #88",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_089": {
        "generic_name": "FORMULARY_SUBSTANCE_089",
        "brand_name": "AegisMed-89",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #89",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_090": {
        "generic_name": "FORMULARY_SUBSTANCE_090",
        "brand_name": "AegisMed-90",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #90",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_091": {
        "generic_name": "FORMULARY_SUBSTANCE_091",
        "brand_name": "AegisMed-91",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #91",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_092": {
        "generic_name": "FORMULARY_SUBSTANCE_092",
        "brand_name": "AegisMed-92",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #92",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_093": {
        "generic_name": "FORMULARY_SUBSTANCE_093",
        "brand_name": "AegisMed-93",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #93",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_094": {
        "generic_name": "FORMULARY_SUBSTANCE_094",
        "brand_name": "AegisMed-94",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #94",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_095": {
        "generic_name": "FORMULARY_SUBSTANCE_095",
        "brand_name": "AegisMed-95",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #95",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_096": {
        "generic_name": "FORMULARY_SUBSTANCE_096",
        "brand_name": "AegisMed-96",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #96",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_097": {
        "generic_name": "FORMULARY_SUBSTANCE_097",
        "brand_name": "AegisMed-97",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #97",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_098": {
        "generic_name": "FORMULARY_SUBSTANCE_098",
        "brand_name": "AegisMed-98",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #98",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_099": {
        "generic_name": "FORMULARY_SUBSTANCE_099",
        "brand_name": "AegisMed-99",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #99",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
    "FORMULARY_SUBSTANCE_100": {
        "generic_name": "FORMULARY_SUBSTANCE_100",
        "brand_name": "AegisMed-100",
        "therapeutic_category": "SPECIALTY_THERAPEUTICS",
        "standard_strength": "100mg",
        "dosage_form": "TABLET",
        "mechanism_of_action": "Targeted cellular receptor modulation protocol #100",
        "standard_dosage_regimen": "1 tablet PO QD with water",
        "adverse_reactions": "Mild headache, transient fatigue",
        "requires_monitoring": False,
    },
}

def get_monograph(generic_name: str) -> Optional[Dict]:
    """Retrieve pharmacology monograph by substance name."""
    return FORMULARY_MONOGRAPHS.get(generic_name.strip().upper())
