"""
AegisCare Enterprise Patient Management System - Evidence-Based Clinical Care Protocols
Standardized hospital clinical algorithms for rapid triage, acute resuscitation, and post-op care.
"""

from typing import Dict, List, Optional

CLINICAL_PRACTICE_PROTOCOLS: Dict[str, Dict] = {
    "PROTO-SEPSIS-01": {
        "protocol_code": "PROTO-SEPSIS-01",
        "title": "Surviving Sepsis Campaign 1-Hour Bundle",
        "category": "CRITICAL_CARE",
        "target_department": "Emergency & ICU",
        "clinical_steps": [
            "1. Measure serum lactate level immediately; remeasure if initial lactate > 2 mmol/L.",
            "2. Obtain blood cultures prior to administration of broad-spectrum antibiotics.",
            "3. Administer broad-spectrum intravenous antimicrobials within 60 minutes of recognition.",
            "4. Rapidly administer 30 mL/kg crystalloid fluid for hypotension or lactate >= 4 mmol/L.",
            "5. Apply vasopressors (Norepinephrine first line) if hypotensive during or after fluid resuscitation to maintain MAP >= 65 mm Hg.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-STEMI-01": {
        "protocol_code": "PROTO-STEMI-01",
        "title": "Acute STEMI Door-to-Balloon 90-Minute Protocol",
        "category": "CARDIOLOGY",
        "target_department": "Emergency Catheterization",
        "clinical_steps": [
            "1. Acquire and interpret 12-lead ECG within 10 minutes of patient emergency arrival.",
            "2. Activate cardiac catheterization laboratory team immediately upon ST-elevation confirmation.",
            "3. Administer Aspirin 324 mg chewable + P2Y12 inhibitor (Ticagrelor 180mg or Clopidogrel 600mg).",
            "4. Establish dual large-bore IV access and administer unfractionated heparin bolus.",
            "5. Transport directly to Cath Lab aiming for primary percutaneous coronary intervention (PCI) < 90 min.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-STROKE-01": {
        "protocol_code": "PROTO-STROKE-01",
        "title": "Acute Ischemic Stroke Thrombolysis (tPA/TNK) Protocol",
        "category": "NEUROLOGY",
        "target_department": "Emergency & Neuro-ICU",
        "clinical_steps": [
            "1. Perform rapid Cincinnati Prehospital Stroke Scale / NIHSS assessment upon triage intake.",
            "2. Non-contrast cranial CT or MRI completed and interpreted within 25 minutes of arrival.",
            "3. Blood glucose check to exclude hypoglycemia mimickers.",
            "4. If ischemic stroke and symptom onset < 4.5 hours with no contraindications, initiate IV thrombolysis.",
            "5. Consider emergent mechanical thrombectomy if large vessel occlusion (LVO) detected on CTA.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-DKA-01": {
        "protocol_code": "PROTO-DKA-01",
        "title": "Diabetic Ketoacidosis (DKA) Resuscitation Protocol",
        "category": "ENDOCRINOLOGY",
        "target_department": "ICU & Step-Down",
        "clinical_steps": [
            "1. Initial fluid resuscitation: 0.9% Normal Saline at 1000 mL/hr for initial 1-2 hours.",
            "2. Check serum potassium: if K+ < 3.3 mEq/L, replete potassium before initiating insulin.",
            "3. Continuous IV regular insulin infusion at 0.1 units/kg/hr; target glucose drop of 50-75 mg/dL/hr.",
            "4. Add 5% Dextrose to IV fluids once blood glucose reaches 200 mg/dL to prevent cerebral edema.",
            "5. Monitor venous blood gas (VBG), electrolytes, and anion gap closure every 2 hours.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-ANAPHYLAXIS-01": {
        "protocol_code": "PROTO-ANAPHYLAXIS-01",
        "title": "Acute Anaphylaxis Emergency Management",
        "category": "ALLERGY_EMERGENCY",
        "target_department": "Resuscitation Bay",
        "clinical_steps": [
            "1. Administer Epinephrine (1:1000) 0.3-0.5 mg Intramuscularly (IM) into anterolateral mid-thigh immediately.",
            "2. Place patient recumbent with lower extremities elevated; avoid upright posture.",
            "3. Administer high-flow supplemental oxygen via non-rebreather mask (10-15 L/min).",
            "4. Establish IV access and infuse 1-2 liters isotonic crystalloid for anaphylactic shock hypotension.",
            "5. Secondary adjunctive agents: Diphenhydramine 50mg IV + Methylprednisolone 125mg IV.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-001": {
        "protocol_code": "PROTO-CLINICAL-001",
        "title": "Standardized Inpatient Clinical Care Pathway #1",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #1.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-002": {
        "protocol_code": "PROTO-CLINICAL-002",
        "title": "Standardized Inpatient Clinical Care Pathway #2",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #2.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-003": {
        "protocol_code": "PROTO-CLINICAL-003",
        "title": "Standardized Inpatient Clinical Care Pathway #3",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #3.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-004": {
        "protocol_code": "PROTO-CLINICAL-004",
        "title": "Standardized Inpatient Clinical Care Pathway #4",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #4.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-005": {
        "protocol_code": "PROTO-CLINICAL-005",
        "title": "Standardized Inpatient Clinical Care Pathway #5",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #5.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-006": {
        "protocol_code": "PROTO-CLINICAL-006",
        "title": "Standardized Inpatient Clinical Care Pathway #6",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #6.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-007": {
        "protocol_code": "PROTO-CLINICAL-007",
        "title": "Standardized Inpatient Clinical Care Pathway #7",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #7.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-008": {
        "protocol_code": "PROTO-CLINICAL-008",
        "title": "Standardized Inpatient Clinical Care Pathway #8",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #8.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-009": {
        "protocol_code": "PROTO-CLINICAL-009",
        "title": "Standardized Inpatient Clinical Care Pathway #9",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #9.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-010": {
        "protocol_code": "PROTO-CLINICAL-010",
        "title": "Standardized Inpatient Clinical Care Pathway #10",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #10.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-011": {
        "protocol_code": "PROTO-CLINICAL-011",
        "title": "Standardized Inpatient Clinical Care Pathway #11",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #11.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-012": {
        "protocol_code": "PROTO-CLINICAL-012",
        "title": "Standardized Inpatient Clinical Care Pathway #12",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #12.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-013": {
        "protocol_code": "PROTO-CLINICAL-013",
        "title": "Standardized Inpatient Clinical Care Pathway #13",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #13.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-014": {
        "protocol_code": "PROTO-CLINICAL-014",
        "title": "Standardized Inpatient Clinical Care Pathway #14",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #14.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-015": {
        "protocol_code": "PROTO-CLINICAL-015",
        "title": "Standardized Inpatient Clinical Care Pathway #15",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #15.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-016": {
        "protocol_code": "PROTO-CLINICAL-016",
        "title": "Standardized Inpatient Clinical Care Pathway #16",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #16.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-017": {
        "protocol_code": "PROTO-CLINICAL-017",
        "title": "Standardized Inpatient Clinical Care Pathway #17",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #17.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-018": {
        "protocol_code": "PROTO-CLINICAL-018",
        "title": "Standardized Inpatient Clinical Care Pathway #18",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #18.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-019": {
        "protocol_code": "PROTO-CLINICAL-019",
        "title": "Standardized Inpatient Clinical Care Pathway #19",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #19.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-020": {
        "protocol_code": "PROTO-CLINICAL-020",
        "title": "Standardized Inpatient Clinical Care Pathway #20",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #20.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-021": {
        "protocol_code": "PROTO-CLINICAL-021",
        "title": "Standardized Inpatient Clinical Care Pathway #21",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #21.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-022": {
        "protocol_code": "PROTO-CLINICAL-022",
        "title": "Standardized Inpatient Clinical Care Pathway #22",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #22.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-023": {
        "protocol_code": "PROTO-CLINICAL-023",
        "title": "Standardized Inpatient Clinical Care Pathway #23",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #23.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-024": {
        "protocol_code": "PROTO-CLINICAL-024",
        "title": "Standardized Inpatient Clinical Care Pathway #24",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #24.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-025": {
        "protocol_code": "PROTO-CLINICAL-025",
        "title": "Standardized Inpatient Clinical Care Pathway #25",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #25.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-026": {
        "protocol_code": "PROTO-CLINICAL-026",
        "title": "Standardized Inpatient Clinical Care Pathway #26",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #26.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-027": {
        "protocol_code": "PROTO-CLINICAL-027",
        "title": "Standardized Inpatient Clinical Care Pathway #27",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #27.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-028": {
        "protocol_code": "PROTO-CLINICAL-028",
        "title": "Standardized Inpatient Clinical Care Pathway #28",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #28.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-029": {
        "protocol_code": "PROTO-CLINICAL-029",
        "title": "Standardized Inpatient Clinical Care Pathway #29",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #29.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-030": {
        "protocol_code": "PROTO-CLINICAL-030",
        "title": "Standardized Inpatient Clinical Care Pathway #30",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #30.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-031": {
        "protocol_code": "PROTO-CLINICAL-031",
        "title": "Standardized Inpatient Clinical Care Pathway #31",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #31.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-032": {
        "protocol_code": "PROTO-CLINICAL-032",
        "title": "Standardized Inpatient Clinical Care Pathway #32",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #32.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-033": {
        "protocol_code": "PROTO-CLINICAL-033",
        "title": "Standardized Inpatient Clinical Care Pathway #33",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #33.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-034": {
        "protocol_code": "PROTO-CLINICAL-034",
        "title": "Standardized Inpatient Clinical Care Pathway #34",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #34.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-035": {
        "protocol_code": "PROTO-CLINICAL-035",
        "title": "Standardized Inpatient Clinical Care Pathway #35",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #35.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-036": {
        "protocol_code": "PROTO-CLINICAL-036",
        "title": "Standardized Inpatient Clinical Care Pathway #36",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #36.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-037": {
        "protocol_code": "PROTO-CLINICAL-037",
        "title": "Standardized Inpatient Clinical Care Pathway #37",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #37.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-038": {
        "protocol_code": "PROTO-CLINICAL-038",
        "title": "Standardized Inpatient Clinical Care Pathway #38",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #38.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-039": {
        "protocol_code": "PROTO-CLINICAL-039",
        "title": "Standardized Inpatient Clinical Care Pathway #39",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #39.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-040": {
        "protocol_code": "PROTO-CLINICAL-040",
        "title": "Standardized Inpatient Clinical Care Pathway #40",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #40.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-041": {
        "protocol_code": "PROTO-CLINICAL-041",
        "title": "Standardized Inpatient Clinical Care Pathway #41",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #41.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-042": {
        "protocol_code": "PROTO-CLINICAL-042",
        "title": "Standardized Inpatient Clinical Care Pathway #42",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #42.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-043": {
        "protocol_code": "PROTO-CLINICAL-043",
        "title": "Standardized Inpatient Clinical Care Pathway #43",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #43.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-044": {
        "protocol_code": "PROTO-CLINICAL-044",
        "title": "Standardized Inpatient Clinical Care Pathway #44",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #44.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-045": {
        "protocol_code": "PROTO-CLINICAL-045",
        "title": "Standardized Inpatient Clinical Care Pathway #45",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #45.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-046": {
        "protocol_code": "PROTO-CLINICAL-046",
        "title": "Standardized Inpatient Clinical Care Pathway #46",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #46.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-047": {
        "protocol_code": "PROTO-CLINICAL-047",
        "title": "Standardized Inpatient Clinical Care Pathway #47",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #47.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-048": {
        "protocol_code": "PROTO-CLINICAL-048",
        "title": "Standardized Inpatient Clinical Care Pathway #48",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #48.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-049": {
        "protocol_code": "PROTO-CLINICAL-049",
        "title": "Standardized Inpatient Clinical Care Pathway #49",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #49.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-050": {
        "protocol_code": "PROTO-CLINICAL-050",
        "title": "Standardized Inpatient Clinical Care Pathway #50",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #50.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-051": {
        "protocol_code": "PROTO-CLINICAL-051",
        "title": "Standardized Inpatient Clinical Care Pathway #51",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #51.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-052": {
        "protocol_code": "PROTO-CLINICAL-052",
        "title": "Standardized Inpatient Clinical Care Pathway #52",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #52.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-053": {
        "protocol_code": "PROTO-CLINICAL-053",
        "title": "Standardized Inpatient Clinical Care Pathway #53",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #53.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-054": {
        "protocol_code": "PROTO-CLINICAL-054",
        "title": "Standardized Inpatient Clinical Care Pathway #54",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #54.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-055": {
        "protocol_code": "PROTO-CLINICAL-055",
        "title": "Standardized Inpatient Clinical Care Pathway #55",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #55.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-056": {
        "protocol_code": "PROTO-CLINICAL-056",
        "title": "Standardized Inpatient Clinical Care Pathway #56",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #56.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-057": {
        "protocol_code": "PROTO-CLINICAL-057",
        "title": "Standardized Inpatient Clinical Care Pathway #57",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #57.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-058": {
        "protocol_code": "PROTO-CLINICAL-058",
        "title": "Standardized Inpatient Clinical Care Pathway #58",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #58.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-059": {
        "protocol_code": "PROTO-CLINICAL-059",
        "title": "Standardized Inpatient Clinical Care Pathway #59",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #59.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-060": {
        "protocol_code": "PROTO-CLINICAL-060",
        "title": "Standardized Inpatient Clinical Care Pathway #60",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #60.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-061": {
        "protocol_code": "PROTO-CLINICAL-061",
        "title": "Standardized Inpatient Clinical Care Pathway #61",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #61.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-062": {
        "protocol_code": "PROTO-CLINICAL-062",
        "title": "Standardized Inpatient Clinical Care Pathway #62",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #62.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-063": {
        "protocol_code": "PROTO-CLINICAL-063",
        "title": "Standardized Inpatient Clinical Care Pathway #63",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #63.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-064": {
        "protocol_code": "PROTO-CLINICAL-064",
        "title": "Standardized Inpatient Clinical Care Pathway #64",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #64.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-065": {
        "protocol_code": "PROTO-CLINICAL-065",
        "title": "Standardized Inpatient Clinical Care Pathway #65",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #65.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-066": {
        "protocol_code": "PROTO-CLINICAL-066",
        "title": "Standardized Inpatient Clinical Care Pathway #66",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #66.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-067": {
        "protocol_code": "PROTO-CLINICAL-067",
        "title": "Standardized Inpatient Clinical Care Pathway #67",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #67.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-068": {
        "protocol_code": "PROTO-CLINICAL-068",
        "title": "Standardized Inpatient Clinical Care Pathway #68",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #68.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-069": {
        "protocol_code": "PROTO-CLINICAL-069",
        "title": "Standardized Inpatient Clinical Care Pathway #69",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #69.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-070": {
        "protocol_code": "PROTO-CLINICAL-070",
        "title": "Standardized Inpatient Clinical Care Pathway #70",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #70.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-071": {
        "protocol_code": "PROTO-CLINICAL-071",
        "title": "Standardized Inpatient Clinical Care Pathway #71",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #71.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-072": {
        "protocol_code": "PROTO-CLINICAL-072",
        "title": "Standardized Inpatient Clinical Care Pathway #72",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #72.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-073": {
        "protocol_code": "PROTO-CLINICAL-073",
        "title": "Standardized Inpatient Clinical Care Pathway #73",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #73.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-074": {
        "protocol_code": "PROTO-CLINICAL-074",
        "title": "Standardized Inpatient Clinical Care Pathway #74",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #74.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-075": {
        "protocol_code": "PROTO-CLINICAL-075",
        "title": "Standardized Inpatient Clinical Care Pathway #75",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #75.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-076": {
        "protocol_code": "PROTO-CLINICAL-076",
        "title": "Standardized Inpatient Clinical Care Pathway #76",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #76.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-077": {
        "protocol_code": "PROTO-CLINICAL-077",
        "title": "Standardized Inpatient Clinical Care Pathway #77",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #77.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-078": {
        "protocol_code": "PROTO-CLINICAL-078",
        "title": "Standardized Inpatient Clinical Care Pathway #78",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #78.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-079": {
        "protocol_code": "PROTO-CLINICAL-079",
        "title": "Standardized Inpatient Clinical Care Pathway #79",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #79.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-080": {
        "protocol_code": "PROTO-CLINICAL-080",
        "title": "Standardized Inpatient Clinical Care Pathway #80",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #80.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-081": {
        "protocol_code": "PROTO-CLINICAL-081",
        "title": "Standardized Inpatient Clinical Care Pathway #81",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #81.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-082": {
        "protocol_code": "PROTO-CLINICAL-082",
        "title": "Standardized Inpatient Clinical Care Pathway #82",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #82.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-083": {
        "protocol_code": "PROTO-CLINICAL-083",
        "title": "Standardized Inpatient Clinical Care Pathway #83",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #83.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-084": {
        "protocol_code": "PROTO-CLINICAL-084",
        "title": "Standardized Inpatient Clinical Care Pathway #84",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #84.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-085": {
        "protocol_code": "PROTO-CLINICAL-085",
        "title": "Standardized Inpatient Clinical Care Pathway #85",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #85.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-086": {
        "protocol_code": "PROTO-CLINICAL-086",
        "title": "Standardized Inpatient Clinical Care Pathway #86",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #86.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-087": {
        "protocol_code": "PROTO-CLINICAL-087",
        "title": "Standardized Inpatient Clinical Care Pathway #87",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #87.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-088": {
        "protocol_code": "PROTO-CLINICAL-088",
        "title": "Standardized Inpatient Clinical Care Pathway #88",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #88.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-089": {
        "protocol_code": "PROTO-CLINICAL-089",
        "title": "Standardized Inpatient Clinical Care Pathway #89",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #89.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-090": {
        "protocol_code": "PROTO-CLINICAL-090",
        "title": "Standardized Inpatient Clinical Care Pathway #90",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #90.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-091": {
        "protocol_code": "PROTO-CLINICAL-091",
        "title": "Standardized Inpatient Clinical Care Pathway #91",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #91.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-092": {
        "protocol_code": "PROTO-CLINICAL-092",
        "title": "Standardized Inpatient Clinical Care Pathway #92",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #92.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-093": {
        "protocol_code": "PROTO-CLINICAL-093",
        "title": "Standardized Inpatient Clinical Care Pathway #93",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #6",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #93.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-094": {
        "protocol_code": "PROTO-CLINICAL-094",
        "title": "Standardized Inpatient Clinical Care Pathway #94",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #7",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #94.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-095": {
        "protocol_code": "PROTO-CLINICAL-095",
        "title": "Standardized Inpatient Clinical Care Pathway #95",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #8",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #95.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-096": {
        "protocol_code": "PROTO-CLINICAL-096",
        "title": "Standardized Inpatient Clinical Care Pathway #96",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #1",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #96.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-097": {
        "protocol_code": "PROTO-CLINICAL-097",
        "title": "Standardized Inpatient Clinical Care Pathway #97",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #2",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #97.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-098": {
        "protocol_code": "PROTO-CLINICAL-098",
        "title": "Standardized Inpatient Clinical Care Pathway #98",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #3",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #98.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-099": {
        "protocol_code": "PROTO-CLINICAL-099",
        "title": "Standardized Inpatient Clinical Care Pathway #99",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #4",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #99.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
    "PROTO-CLINICAL-100": {
        "protocol_code": "PROTO-CLINICAL-100",
        "title": "Standardized Inpatient Clinical Care Pathway #100",
        "category": "GENERAL_MEDICINE",
        "target_department": "Ward Unit #5",
        "clinical_steps": [
            "Step 1: Perform baseline clinical evaluation and risk stratification #100.",
            "Step 2: Order standard diagnostic laboratory investigations and monitoring telemetry.",
            "Step 3: Administer scheduled pharmacotherapeutic interventions as indicated in monograph.",
            "Step 4: Conduct nursing vitals review every 4 hours with pain score documentation.",
            "Step 5: Review discharge criteria and schedule outpatient physician follow-up.",
        ],
        "review_interval_months": 12,
        "is_active": True,
    },
}

def get_protocol(code: str) -> Optional[Dict]:
    """Retrieve evidence-based clinical protocol."""
    return CLINICAL_PRACTICE_PROTOCOLS.get(code.strip().upper())
